apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rbac-go-certificate
spec:
  secretName: rbac-go-crt-secret
  dnsNames:
    - rbac.deagwon.com
  issuerRef:
    name: rbac-go-issuer
    kind: Issuer
