version: "3.7"

services:
  rbac-go-prod:
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: production
    env_file:
      - ../.env
    ports:
      - 8000:8000
  
volumes:
  dbdata-dev:
