version: "3.7"

services:
  rbac-go:
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: builder
    volumes:
      - ../:/home/rbac/workdir
    env_file:
      - ../.env
    stdin_open: true
    tty: true
  rbac-go-prod:
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: production
    env_file:
      - ../.env
    ports:
      - 8000:8000
  database-dev:
    image: mariadb:10.8.2
    restart: always
    volumes:
      - dbdata-dev:/var/lib/mysql
    env_file:
      - .env.db
  
volumes:
  dbdata-dev:
