version: "3.7"

services:
  rbac-go:
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: builder
    volumes:
      - ../:/home/rbac/workdir
    env_file:
      - ../.env
    ports:
      - 8001:8000
    stdin_open: true
    tty: true
  rbac-go-prod:
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: production
    env_file:
      - ../.env
    ports:
      - 8000:8000
