version: "3.7"

services:
  rbac-go:
    build:
      context: ../
      dockerfile: ./Dockerfile  
      target: builder
    volumes:
      - ../:/root/workdir
    env_file:
      - ../.env
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    
  database:
    image: mariadb
    container_name: database
    ports:
      - 3306:3306
    restart: always
    env_file:
      - .env.db
    volumes:
      - mariadb:/var/lib/mysql
      - ./db-data/conf.d:/etc/mysql/conf.d
volumes:
  mariadb:
    driver: local
